### ISSUE TITLE
DISCORD Help

### ISSUE THREAD

**Issue by paldog** [ceifa/lory-gmod-servers#86]
Hey! can you bring me help with my discord server config?
i want to add my discord group to the rewards and to the ulx commands i think? because i saw a folder called ulx lory but i dont know in what place i need to add my discord server id or something else.
if you help me with that i be very happy… thanksbtw

**Comment by ceifa** [comment]
You will need a discord bot which send commands to the server console. We cannot share our discord bot code because of potential security issues on it. To create the bot we are using https://pylon.bot/ and to receive the commands we are using the pterodactyl api: https://dashflo.net/docs/api/pterodactyl/v0.7/#send-console-command
